### PR TITLE
datastore: allow field names ending in '.'

### LINKED ISSUE #41: datastore: field name cannot end with '.'
I'm trying to update to the latest appengine pkg in our project (from a very old version), but running in to problems with our PropertyLoadSaver.

When embedding a type like this:
```
type SpecialTime struct {
	time.Time
}
```
and then using it in an entity saved in datastore, the datastore field will end with a dot. Which is not allowed due to [this loc](https://github.com/golang/appengine/blob/master/datastore/load.go#L91).

Here is a minimal repro: https://github.com/fredr/datastoreloadsavetest
it uses our current version of the appengien pkg (267c27e7492265b84fc6719503b14a1e17975d79) and works fine, the props will be (notice the ending dot in EmbeddedTime):
```
[{Name:EmbeddedTime. Value:2016-12-19 10:49:23.280860142 +0000 UTC NoIndex:false Multiple:false} {Name:NormalTime Value:2016-12-19 10:49:23.280860121 +0000 UTC NoIndex:false Multiple:false}]
```

Updating the appengine packages to the latest will produce this error:
```
datastore: cannot load field "EmbeddedTime." into a "appenginetest.TestEntity": field name cannot end with '.'
```

### PR DESCRIPTION
**Pull request by adams-sarah**
restructures Load logic to map fields ending in '.' to the anonymous
struct field specified in the codec

Fixes #41

### CODE REVIEW

File: datastore/datastore_test.go [hunk 1]
```diff
@@ -1413,6 +1423,22 @@ var testCases = []testCase{
...
+		"embedded time field",
+		&SpecialTime{MyTime: EmbeddedTime{now}},
+		&SpecialTime{MyTime: EmbeddedTime{now}},
+		"",
+		"",
+	},
+	{
+		"embedded time load",
+		&PropertyList{
+			Property{Name: "MyTime.", Value: now, NoIndex: false, Multiple: false},
```
Comment (broady) [inline datastore/datastore_test.go]: Should it maybe be encoded as "MyTime.Time"? Or is it just not possible to change the encoder now?

Comment (adams-sarah) [inline datastore/datastore_test.go]: Yea, I argued for that too. But it would break backwards compatibility. 
See discussion here: https://github.com/golang/appengine/issues/41

Unfortunately, this is broken on the cloud.google.com/go/datastore side too, and I'm going to have to do something like "MyTime.Time" on that side. So interop btwn the two packages will be broken for users with these embedded times or geo points.

**Comment by adams-sarah** [comment]
@adamtanner thoughts?
