### PR TITLE
Ensure at least one log flush happens before request ends

### LINKED ISSUE #163: google.golang.org/appengine/log isn't compatible with GAE/Go 1.11
I am trying to migrate apps with App Engine API to Go 1.11 runtime for App Engine standard.
`google.golang.org/appengine/log` seems broken in Go 1.11 runtime because log loss is happen.

Example to reproduce

```go
package main

import (
	"google.golang.org/appengine"
	"google.golang.org/appengine/log"
	"net/http"
)

func main() {
	http.HandleFunc("/write_log_gae", func(w http.ResponseWriter, req *http.Request) {
		ctx := appengine.NewContext(req)
		log.Infof(ctx, "test")
		w.WriteHeader(http.StatusOK)
	})
	appengine.Main()
}
```

Single call of `/write_log_gae` emits three top level logs.
- request log in request
- log level prefixed line in stderr
- `internal.flushLog` RPC log in stderr

Frequently, RPC log says `Call error 3: invalid security ticket` and request log doesn't have apps log.

This screenshot is result of calling twice. The bottom half doesn't have app log(Severity is not set from child.)

### PR DESCRIPTION
**Pull request by sbuss**
Fixes #163

The Go 1.11 runtime on GAE Standard is closing the connection before the logs are flushed, which invalidates the security ticket needed to send logs to stackdriver. This can be mitigated by forcing a log flush to happen before the request closes.

### CODE REVIEW

**Comment by vvakame** [comment]
👀 how is the progress? i need this changes...

**Comment by vvakame** [comment]
👀 how is the progress? i need this changes...

**Comment by sbuss** [comment]
@vvakame Right now this is targeted for a November 1st release. I'd love to get it out earlier, but it breaks compatibility with Go 1.6. We will drop support for Go 1.6 on November 1st, so it can merge then.

In the meantime, can you reference the commit c28ce1c?

File: internal/api_test.go [hunk 1]
```diff
@@ -250,43 +251,79 @@ func TestDelayedLogFlushing(t *testing.T) {
...
-	if d := time.Since(start); d > 10*time.Millisecond {
-		t.Errorf("handleHTTP took %v, want under 10ms", d)
+	var wg sync.WaitGroup
+	wg.Add(1)
+	go func() {
+		defer wg.Done()
+		handleHTTP(w, r)
+	}()
+	// Check that the log flush eventually comes in.
+	time.Sleep(1200 * time.Millisecond)
```
Comment (mtraver) [inline internal/api_test.go]: Was this meant to be 1500 ms? Comment below says 1.5s.

**Comment by sbuss** [comment]
> Much of this looks the same as the PR that drops support for < Go 1.8 though. Will this be rebased once that PR is merged so it's just the log changes?

Ah, yes, I had to merge that branch because these changes are incompatible with 1.6. I will rebase after I merge it.

**Comment by sbuss** [comment]
@mtraver I rebased if you want to take another look

File: internal/api_test.go (hunk 1 above)
Comment (sbuss) [reply internal/api_test.go]: The comment was wrong; fixed

File: internal/api.go [hunk 2]
```diff
@@ -129,7 +129,14 @@ func handleHTTP(w http.ResponseWriter, r *http.Request) {
 		flushes++
 	}
 	c.pendingLogs.Unlock()
-	go c.flushLog(false)
+	var wg sync.WaitGroup
+	wg.Add(1)
```
Comment (zombiezen) [inline internal/api.go]: A channel would suffice here:

```go
flushed := make(chan struct{})
go func() {
  defer close(flushed)
  c.flushLog(true)
}()
// ...
<-flushed
```

File: internal/api_test.go [hunk 3]
```diff
@@ -250,43 +251,79 @@ func TestDelayedLogFlushing(t *testing.T) {
...
 	}
 	w := httptest.NewRecorder()
 
-	// Check that log flushing does not hold up the HTTP response.
-	start := time.Now()
-	handleHTTP(w, r)
-	if d := time.Since(start); d > 10*time.Millisecond {
-		t.Errorf("handleHTTP took %v, want under 10ms", d)
+	var wg sync.WaitGroup
+	wg.Add(1)
```
Comment (zombiezen) [inline internal/api_test.go]: Same comment here.

Comment (sbuss) [reply internal/api_test.go]: done
